import ArrowSortSvg from "@/assets/icons/arrow-sort.svg";
import CalendarAddSvg from "@/assets/icons/calendar-add.svg";
import ChatSvg from "@/assets/icons/chat.svg";
import ChevronDownSvg from "@/assets/icons/chevron-down.svg";
import ChevronLeftSvg from "@/assets/icons/chevron-left.svg";
import CircleCancelSvg from "@/assets/icons/circle-cancel.svg";
import CloseSvg from "@/assets/icons/close.svg";
import CoinSvg from "@/assets/icons/coin.svg";
import LinkSvg from "@/assets/icons/link.svg";
import LocationAddSvg from "@/assets/icons/location-add.svg";
import LocationErrorSvg from "@/assets/icons/location-error.svg";
import LocationSvg from "@/assets/icons/location.svg";
import MenuDotVerticalSvg from "@/assets/icons/menu-dot-vertical.svg";
import MenuHamburgerSvg from "@/assets/icons/menu-hamburger.svg";
import PlusSvg from "@/assets/icons/plus.svg";
import ReactionStarSvg from "@/assets/icons/reaction-star.svg";
import SavedAddSvg from "@/assets/icons/saved-add.svg";
import SavedSvg from "@/assets/icons/saved.svg";
import SearchSvg from "@/assets/icons/search.svg";
import SettingsSvg from "@/assets/icons/settings.svg";
import ShareSvg from "@/assets/icons/share.svg";
import TimeClockSvg from "@/assets/icons/time-clock.svg";
import TrashSvg from "@/assets/icons/trash.svg";
import WriteAddSvg from "@/assets/icons/write-add.svg";
import WriteSvg from "@/assets/icons/write.svg";

import { createIcon } from "./create-icon";

export type { IconProps } from "./create-icon";

export const ArrowSortIcon = createIcon(ArrowSortSvg, "ArrowSortIcon");
export const CalendarAddIcon = createIcon(CalendarAddSvg, "CalendarAddIcon");
export const ChatIcon = createIcon(ChatSvg, "ChatIcon");
export const ChevronDownIcon = createIcon(ChevronDownSvg, "ChevronDownIcon");
export const ChevronLeftIcon = createIcon(ChevronLeftSvg, "ChevronLeftIcon");
export const CircleCancelIcon = createIcon(CircleCancelSvg, "CircleCancelIcon");
export const CloseIcon = createIcon(CloseSvg, "CloseIcon");
export const CoinIcon = createIcon(CoinSvg, "CoinIcon");
export const LinkIcon = createIcon(LinkSvg, "LinkIcon");
export const LocationAddIcon = createIcon(LocationAddSvg, "LocationAddIcon");
export const LocationErrorIcon = createIcon(LocationErrorSvg, "LocationErrorIcon");
export const LocationIcon = createIcon(LocationSvg, "LocationIcon");
export const MenuDotVerticalIcon = createIcon(MenuDotVerticalSvg, "MenuDotVerticalIcon");
export const MenuHamburgerIcon = createIcon(MenuHamburgerSvg, "MenuHamburgerIcon");
export const PlusIcon = createIcon(PlusSvg, "PlusIcon");
export const ReactionStarIcon = createIcon(ReactionStarSvg, "ReactionStarIcon");
export const SavedAddIcon = createIcon(SavedAddSvg, "SavedAddIcon");
export const SavedIcon = createIcon(SavedSvg, "SavedIcon");
export const SearchIcon = createIcon(SearchSvg, "SearchIcon");
export const SettingsIcon = createIcon(SettingsSvg, "SettingsIcon");
export const ShareIcon = createIcon(ShareSvg, "ShareIcon");
export const TimeClockIcon = createIcon(TimeClockSvg, "TimeClockIcon");
export const TrashIcon = createIcon(TrashSvg, "TrashIcon");
export const WriteAddIcon = createIcon(WriteAddSvg, "WriteAddIcon");
export const WriteIcon = createIcon(WriteSvg, "WriteIcon");
