import { QueryClient } from '@tanstack/react-query';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { PackingCoordinator } from './coordinator';
import { PackingApiError, packingApi } from '@/lib/api/rooms/packing';
import type { PackingList } from './types';
vi.mock('@/lib/api/rooms/packing', () => ({
  PackingApiError: class extends Error { constructor(public status:number,public code:string,message:string){super(message);} },
  packingApi: { get:vi.fn(),initialize:vi.fn(),createPart:vi.fn(),renamePart:vi.fn(),deletePart:vi.fn(),createItem:vi.fn(),renameItem:vi.fn(),checkItem:vi.fn(),deleteItem:vi.fn(),restoreItem:vi.fn(),saveMemo:vi.fn(),deleteMemo:vi.fn() },
}));
const room='11111111-1111-4111-8111-111111111111';
function list(version=0):PackingList { return {id:1,roomId:room,ownerUserId:7,version,initializedAt:'2026-09-20T00:00:00Z',parts:[{id:2,name:'서류',position:0,column:0,items:[{id:3,partId:2,name:'여권',checked:false,position:0,memo:null}]}]}; }
function setup(){const client=new QueryClient({defaultOptions:{queries:{retry:false}}});const c=new PackingCoordinator(client,room,7);return {client,c};}
function deferred<T>(){let resolve!:(x:T)=>void;let reject!:(x:unknown)=>void;const promise=new Promise<T>((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};}
afterEach(()=>{vi.resetAllMocks();vi.useRealTimers();});
describe('packing admission and recovery',()=>{
 it('deduplicates admission and initializes only exact not-initialized, retaining empty list',async()=>{
  const {c}=setup();vi.mocked(packingApi.get).mockRejectedValue(new PackingApiError(404,'PACKING_LIST_NOT_INITIALIZED','missing'));
  vi.mocked(packingApi.initialize).mockResolvedValue({...list(),parts:[]});
  await Promise.all([c.refresh(),c.refresh(),c.refresh()]);
  expect(packingApi.get).toHaveBeenCalledTimes(1);expect(packingApi.initialize).toHaveBeenCalledTimes(1);expect(c.getSnapshot().data?.parts).toEqual([]);
  vi.mocked(packingApi.get).mockResolvedValue({...list(),parts:[]});await c.refresh();expect(packingApi.initialize).toHaveBeenCalledTimes(1);
 });
 it.each([[404,'UNKNOWN'],[403,'NOT_ROOM_MEMBER'],[404,'ROOM_NOT_FOUND'],[429,'TOO_MANY_REQUESTS']])('never initializes arbitrary %i %s',async(status,code)=>{const {c}=setup();vi.mocked(packingApi.get).mockRejectedValue(new PackingApiError(status,code,'error'));await c.refresh();expect(packingApi.initialize).not.toHaveBeenCalled();expect(packingApi.get).toHaveBeenCalledTimes(1);});
 it('retries network GET once but never loops initialization after its failure',async()=>{const {c}=setup();vi.mocked(packingApi.get).mockRejectedValue(new TypeError('offline'));await c.refresh();expect(packingApi.get).toHaveBeenCalledTimes(2);expect(c.getSnapshot().status).toBe('error');
 vi.mocked(packingApi.get).mockRejectedValue(new PackingApiError(404,'PACKING_LIST_NOT_INITIALIZED','missing'));vi.mocked(packingApi.initialize).mockRejectedValue(new TypeError('offline'));await c.refresh();await c.refresh();expect(packingApi.initialize).toHaveBeenCalledTimes(1);await c.refresh(true);expect(packingApi.initialize).toHaveBeenCalledTimes(2);});
 it('locks synchronously, optimistically checks, defers focus reads and applies server entity/version',async()=>{const {c}=setup();vi.mocked(packingApi.get).mockResolvedValue(list());await c.refresh();const pending=deferred<Awaited<ReturnType<typeof packingApi.checkItem>>>();vi.mocked(packingApi.checkItem).mockReturnValue(pending.promise);
 const first=c.execute({type:'checkItem',id:3,checked:true});const second=await c.execute({type:'checkItem',id:3,checked:false});expect(second.kind).toBe('blocked');await Promise.resolve();await c.refresh();expect(packingApi.get).toHaveBeenCalledTimes(1);
 pending.resolve({version:1,item:{...list().parts[0].items[0],checked:true}});vi.mocked(packingApi.get).mockResolvedValue({...list(1),parts:[{...list().parts[0],items:[{...list().parts[0].items[0],checked:true}]}]});await first;expect(packingApi.checkItem).toHaveBeenCalledTimes(1);expect(c.getSnapshot().data?.version).toBe(1);expect(c.getSnapshot().data?.parts[0].items[0].checked).toBe(true);expect(packingApi.get).toHaveBeenCalledTimes(2);
 });
 it('keeps a confirmed write when follow-up GET fails and blocks writes until recovery',async()=>{const {c}=setup();vi.mocked(packingApi.get).mockResolvedValue(list());await c.refresh();vi.mocked(packingApi.checkItem).mockResolvedValue({version:1,item:{...list().parts[0].items[0],checked:true}});vi.mocked(packingApi.get).mockRejectedValue(new TypeError('offline'));expect((await c.execute({type:'checkItem',id:3,checked:true})).kind).toBe('success');expect(c.getSnapshot().status).toBe('sync-error');expect(c.getSnapshot().data?.parts[0].items[0].checked).toBe(true);expect((await c.execute({type:'renamePart',id:2,name:'new'})).kind).toBe('blocked');vi.mocked(packingApi.get).mockResolvedValue(list(1));await c.refresh(true);expect(c.getSnapshot().status).toBe('ready');expect(c.getSnapshot().message).toBeNull();});
 it('rolls back uncertain writes, never retries them, reconciles and requires explicit resave',async()=>{const {c}=setup();vi.mocked(packingApi.get).mockResolvedValue(list());await c.refresh();vi.mocked(packingApi.checkItem).mockRejectedValue(new TypeError('lost response'));vi.mocked(packingApi.get).mockRejectedValue(new TypeError('offline'));await c.execute({type:'checkItem',id:3,checked:true});expect(c.getSnapshot().data?.parts[0].items[0].checked).toBe(false);expect(c.getSnapshot().status).toBe('uncertain');expect(packingApi.checkItem).toHaveBeenCalledTimes(1);expect((await c.execute({type:'checkItem',id:3,checked:true})).kind).toBe('blocked');});
 it.each([400,409,410,429])('rolls back definite %i with no mutation retry',async(status)=>{const {c}=setup();vi.mocked(packingApi.get).mockResolvedValue(list());await c.refresh();vi.mocked(packingApi.checkItem).mockRejectedValue(new PackingApiError(status,'PACKING_CONFLICT','retry explicitly'));await c.execute({type:'checkItem',id:3,checked:true});expect(c.getSnapshot().data?.parts[0].items[0].checked).toBe(false);expect(packingApi.checkItem).toHaveBeenCalledTimes(1);});
 it('invalidates pending generation and removes cache on scope loss',async()=>{const {c,client}=setup();vi.mocked(packingApi.get).mockResolvedValue(list());await c.refresh();const pending=deferred<Awaited<ReturnType<typeof packingApi.checkItem>>>();vi.mocked(packingApi.checkItem).mockReturnValue(pending.promise);const write=c.execute({type:'checkItem',id:3,checked:true});await Promise.resolve();await Promise.resolve();c.dispose();pending.resolve({version:1,item:{...list().parts[0].items[0],checked:true}});await write;expect(c.getSnapshot().data).toBeNull();expect(client.getQueryData(['packing',room,7])).toBeUndefined();});
 it('rejects data for another principal and purges cached private content on access loss',async()=>{const {c,client}=setup();vi.mocked(packingApi.get).mockResolvedValue(list());await c.refresh();vi.mocked(packingApi.get).mockRejectedValue(new PackingApiError(403,'NOT_ROOM_MEMBER','gone'));await c.refresh();expect(c.getSnapshot().status).toBe('revoked');expect(c.getSnapshot().data).toBeNull();expect(client.getQueryData(['packing',room,7])).toBeUndefined();});
 it('does not lower committed version with a stale read',async()=>{const {c}=setup();vi.mocked(packingApi.get).mockResolvedValue(list(4));await c.refresh();vi.mocked(packingApi.get).mockResolvedValue(list(2));await c.refresh();expect(c.getSnapshot().data?.version).toBe(4);expect(c.getSnapshot().status).toBe('sync-error');});
 it('refetches before nonempty delete confirmation; cancel sends no DELETE',async()=>{const {c}=setup();vi.mocked(packingApi.get).mockResolvedValue(list());await c.refresh();await c.prepareDelete('part',2);expect(packingApi.get).toHaveBeenCalledTimes(2);expect(c.getSnapshot().confirmation).toMatchObject({kind:'part',id:2,version:0});c.cancelConfirmation();expect(packingApi.deletePart).not.toHaveBeenCalled();});
 it('memo-free delete stays visible until success; undo uses original ID and cannot recreate missing parent',async()=>{const {c}=setup();vi.mocked(packingApi.get).mockResolvedValue(list());await c.refresh();const pending=deferred<Awaited<ReturnType<typeof packingApi.deleteItem>>>();vi.mocked(packingApi.deleteItem).mockReturnValue(pending.promise);const deletion=c.prepareDelete('item',3);await Promise.resolve();await Promise.resolve();expect(c.getSnapshot().data?.parts[0].items).toHaveLength(1);pending.resolve({version:1,deletedItemId:3,serverTime:'2026-09-20T00:00:00Z',undo:{token:'test-only-token',expiresAt:'2026-09-20T00:00:10Z'}});vi.mocked(packingApi.get).mockResolvedValue({...list(1),parts:[{...list().parts[0],items:[]}]});await deletion;expect(c.getSnapshot().undo).toHaveLength(1);vi.mocked(packingApi.get).mockResolvedValue({...list(2),parts:[]});await c.refresh();expect(c.getSnapshot().undo).toHaveLength(0);await c.restore(3);expect(packingApi.restoreItem).not.toHaveBeenCalled();c.dispose();});
});

it('does not send a confirmation after a read advances its reviewed version while cancellation settles',async()=>{
 const {c,client}=setup();vi.mocked(packingApi.get).mockResolvedValue(list());await c.refresh();await c.prepareDelete('part',2);
 const read=deferred<PackingList>();vi.mocked(packingApi.get).mockReturnValue(read.promise);const refresh=c.refresh();
 const cancelled=deferred<void>();vi.spyOn(client,'cancelQueries').mockReturnValue(cancelled.promise);
 const confirmation=c.confirmDelete();read.resolve(list(1));await refresh;cancelled.resolve();await confirmation;
 expect(packingApi.deletePart).not.toHaveBeenCalled();expect(c.getSnapshot().confirmation).toBeNull();expect(c.getSnapshot().status).toBe('ready');
});
it('never publishes another owner response into the admitted query cache',async()=>{
 const {c,client}=setup();const seen:unknown[]=[];client.getQueryCache().subscribe(()=>{const d=client.getQueryData<PackingList>(['packing',room,7]);if(d)seen.push(d.ownerUserId);});
 vi.mocked(packingApi.get).mockResolvedValue({...list(),ownerUserId:8});await c.refresh();expect(seen).not.toContain(8);expect(c.getSnapshot().status).toBe('revoked');
});
it('rejects invalid local drafts without speculative display or recovery request',async()=>{
 const {c}=setup();vi.mocked(packingApi.get).mockResolvedValue(list());await c.refresh();await c.execute({type:'renamePart',id:2,name:' '.repeat(51)});
 expect(packingApi.renamePart).not.toHaveBeenCalled();expect(packingApi.get).toHaveBeenCalledTimes(1);expect(c.getSnapshot().status).toBe('ready');expect(c.getSnapshot().data?.parts[0].name).toBe('서류');
});
it('expires undo by monotonic server-relative remaining time even if wall clock changes',async()=>{
 vi.useFakeTimers({toFake:['setTimeout','clearTimeout','performance']});const {c}=setup();vi.mocked(packingApi.get).mockResolvedValue(list());await c.refresh();
 const response=deferred<Awaited<ReturnType<typeof packingApi.deleteItem>>>();vi.mocked(packingApi.deleteItem).mockReturnValue(response.promise);
 const deletion=c.prepareDelete('item',3);await Promise.resolve();await Promise.resolve();await vi.advanceTimersByTimeAsync(3000);
 response.resolve({version:1,deletedItemId:3,serverTime:'2026-09-20T00:00:00Z',undo:{token:'test-only-token',expiresAt:'2026-09-20T00:00:10Z'}});vi.mocked(packingApi.get).mockResolvedValue({...list(1),parts:[{...list().parts[0],items:[]}]});await deletion;
 expect(c.getSnapshot().undo[0].remainingMs).toBe(7000);vi.setSystemTime(new Date('2030-01-01'));await vi.advanceTimersByTimeAsync(7000);expect(c.getSnapshot().undo).toEqual([]);await c.restore(3);expect(packingApi.restoreItem).not.toHaveBeenCalled();c.dispose();
});
it('leaves final 401 navigation to existing session teardown',async()=>{const {c}=setup();vi.mocked(packingApi.get).mockResolvedValue(list());await c.refresh();vi.mocked(packingApi.get).mockRejectedValue(new PackingApiError(401,'UNAUTHORIZED','expired'));await c.refresh();expect(c.getSnapshot().status).toBe('revoked');expect(c.getSnapshot().exitToHome).toBe(false);});
it.each([[404,'PACKING_UNDO_NOT_FOUND'],[409,'PACKING_UNDO_USED'],[409,'PACKING_RESTORE_CONFLICT'],[410,'PACKING_UNDO_EXPIRED'],[409,'PACKING_CAPACITY_EXCEEDED']])('never resurrects locally when restore rejects %i %s',async(status,code)=>{
 const {c}=setup();vi.mocked(packingApi.get).mockResolvedValue(list());await c.refresh();vi.mocked(packingApi.deleteItem).mockResolvedValue({version:1,deletedItemId:3,serverTime:'2026-09-20T00:00:00Z',undo:{token:'11111111-1111-4111-8111-111111111111',expiresAt:'2026-09-20T00:00:10Z'}});const deleted={...list(1),parts:[{...list().parts[0],items:[]}]};vi.mocked(packingApi.get).mockResolvedValue(deleted);await c.prepareDelete('item',3);
 const response=deferred<Awaited<ReturnType<typeof packingApi.restoreItem>>>();const started=deferred<void>();vi.mocked(packingApi.restoreItem).mockImplementation(()=>{started.resolve();return response.promise;});const restoring=c.restore(3);await started.promise;expect(c.getSnapshot().data?.parts[0].items[0]).toEqual(list().parts[0].items[0]);response.reject(new PackingApiError(status,code,'restore rejected'));await restoring;expect(c.getSnapshot().data?.parts[0].items).toEqual([]);expect(c.getSnapshot().undo).toEqual([]);expect(packingApi.restoreItem).toHaveBeenCalledTimes(1);c.dispose();
});
it('ignores late initialization after scope disposal',async()=>{const {c,client}=setup();vi.mocked(packingApi.get).mockRejectedValue(new PackingApiError(404,'PACKING_LIST_NOT_INITIALIZED','missing'));const init=deferred<PackingList>();vi.mocked(packingApi.initialize).mockReturnValue(init.promise);const admission=c.refresh();await Promise.resolve();await Promise.resolve();await Promise.resolve();c.dispose();init.resolve(list());await admission;expect(c.getSnapshot().data).toBeNull();expect(client.getQueryData(['packing',room,7])).toBeUndefined();});
it('confirmation-required from server never automatically sends a confirmed delete',async()=>{const {c}=setup();vi.mocked(packingApi.get).mockResolvedValue(list());await c.refresh();const latest=list(1);latest.parts[0].items[0].memo={id:3,itemId:3,content:'new memo'};vi.mocked(packingApi.deleteItem).mockRejectedValue(new PackingApiError(409,'PACKING_CONFIRMATION_REQUIRED','memo'));vi.mocked(packingApi.get).mockResolvedValue(latest);await c.prepareDelete('item',3);expect(packingApi.deleteItem).toHaveBeenCalledExactlyOnceWith(room,3,0,false);expect(c.getSnapshot().confirmation).toBeNull();await c.prepareDelete('item',3);expect(c.getSnapshot().confirmation).toMatchObject({id:3,version:1});expect(packingApi.deleteItem).toHaveBeenCalledTimes(1);c.dispose();});
